source :rubygems

gem 'rake'
gem 'highline'
gem 'awesome_print'

gem 'rest-client', :require => 'rest_client'

gem 'tilt'

group :markup do
  gem 'RedCloth', :require => 'redcloth'
  gem 'haml'
  gem 'erubis'
  gem 'liquid'
  gem 'rdiscount'
end

group :styles do
  gem 'sass'
  gem 'less'
end

group :scripts do
  gem 'therubyracer'
  gem 'coffee-script'
end
