source :rubygems

gem 'rake'
gem 'highline'
gem 'awesome_print'

gem 'rest-client', :require => 'rest_client'

gem 'tilt' # used to compile the markup
gem 'erector' # typically used in helpers
gem 'ratom' # used to generate the atom feed

gem 'sinatra'
gem 'rerun'
gem 'rb-inotify', '~> 0.8.8'

group :markup do
  gem 'RedCloth', :require => 'redcloth'
  gem 'haml'
  gem 'erubis'
  gem 'liquid'
  gem 'rdiscount'
end

group :styles do
  gem 'sass'
  gem 'less'
end

group :scripts do
  gem 'therubyracer', :require => 'v8', :platforms => :ruby
  gem 'coffee-script'
end
